## measure of cental tendency

#  mean , median ,and mode

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
        

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.mean(arr)

4.5

In [14]:
np.median(arr)

4.5

In [15]:
#  if we insert an outlier

arr = [1,2,3,4,4,5,6,100]

In [16]:
arr

[1, 2, 3, 4, 4, 5, 6, 100]

In [17]:
np.mean(arr)

15.625

In [18]:
np.median(arr)  # median is least affected by outliers

4.0

In [2]:
from scipy import stats

In [20]:
stats.mode(arr)

/tmp/ipykernel_70/1379525054.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  stats.mode(arr)


ModeResult(mode=array([4]), count=array([2]))

# measure of dispersion - variance , standard deviation

In [21]:
arr

[1, 2, 3, 4, 4, 5, 6, 100]

In [22]:
np.var(arr)   # variance tells how much the data set is spread

1019.234375

In [23]:
np.std(arr)

31.92545027090456

# covariance and correlation

In [24]:
import seaborn as sns

In [25]:
df = sns.load_dataset("healthexp")

In [26]:
df.head()

Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [27]:
df.cov()

/tmp/ipykernel_70/1545644723.py:1: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.cov()


Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

In [28]:
df.corr(method = "pearson")

/tmp/ipykernel_70/3025111369.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr(method = "pearson")


Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [29]:
df.corr(method = "spearman")

/tmp/ipykernel_70/636568451.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr(method = "spearman")


Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [30]:
arr

[1, 2, 3, 4, 4, 5, 6, 100]

In [32]:
arr1 = np.array([9,8,6,5,4,3,2,1])

In [33]:
arr1

array([9, 8, 6, 5, 4, 3, 2, 1])

In [35]:
np.cov(arr1)

array(7.92857143)

In [36]:
np.var(arr1)

6.9375

In [37]:
np.cov(arr1,arr)

array([[   7.92857143,  -55.39285714],
       [ -55.39285714, 1164.83928571]])

In [42]:
stats.pearsonr(arr1,arr)

PearsonRResult(statistic=-0.5763990949697633, pvalue=0.134768547266626)

In [43]:
stats.spearmanr(arr1,arr)

SpearmanrResult(correlation=-0.9940297973880048, pvalue=5.296153515645123e-07)